export const dataProjects = [
  {
    id: 1,
    product: 'Gorgeous Rubber Gloves',
    price: 165,
    stock: 32,
    sales: 65,
    description: 'High quality with Competitive Price',
  },
  {
    id: 2,
    product: 'Volumizer Hot Air Brush',
    price: 34,
    stock: 56,
    sales: 19,
    description: 'Less Frizz and helps reduce hair damage',
  },
  {
    id: 3,
    product: 'French Terry Jogger',
    price: 165,
    stock: 32,
    sales: 65,
    description: 'Athletic pant in lightweight French terry fabrication',
  },
  {
    id: 4,
    product: 'Gorgeous Plastic Tuna',
    price: 165,
    stock: 32,
    sales: 65,
    description: 'High quality with Competitive Price',
  },
  {
    id: 5,
    product: 'Tasty Concrete Hat',
    price: 165,
    stock: 32,
    sales: 65,
    description: 'High quality with Competitive Price',
  },
  {
    id: 6,
    product: 'Humidifier Mineral Absorption ',
    price: 165,
    stock: 32,
    sales: 65,
    description: '10 x absorption pads per packaged box',
  },
  {
    id: 7,
    product: 'Dramatic Faux Mink Eyelashes Pack',
    price: 165,
    stock: 32,
    sales: 65,
    description: 'Using the premium materials',
  },
  {
    id: 8,
    product: 'Battery Operated',
    price: 165,
    stock: 32,
    sales: 65,
    description: 'Smart plugs that work with Alexa and Google',
  },
  {
    id: 9,
    product: 'Spice Jars',
    price: 165,
    stock: 32,
    sales: 65,
    description: 'The drawer spice rack is made of safe and high quality PP plastic material',
  },
  {
    id: 10,
    product: 'LED Light up Rings Toys',
    price: 165,
    stock: 32,
    sales: 65,
    description: 'Each Box Contains 10 pack led light up rings',
  },
  {
    id: 11,
    product: 'Convenience Kits International',
    price: 165,
    stock: 32,
    sales: 65,
    description: 'Womens Deluxe 10',
  },
  {
    id: 12,
    product: 'Neutrogena Makeup Remover Facial Cleansing',
    price: 165,
    stock: 32,
    sales: 65,
    description: 'Remover Facial Cleansing',
  },
  {
    id: 13,
    product: 'Black Disposable Face Masks',
    price: 165,
    stock: 32,
    sales: 65,
    description: '100 Pack Black Face Masks 3 Ply Filter Protection',
  },
  {
    id: 14,
    product: 'Facial Cleansing Brush by Olay Regenerist',
    price: 165,
    stock: 32,
    sales: 65,
    description: 'Face Exfoliator with 2 Brush Heads',
  },
  {
    id: 15,
    product: 'celavi Essence Facial Face Mask Paper Sheet',
    price: 165,
    stock: 32,
    sales: 65,
    description: 'Korea Skin Care Moisturizing 12 Pack (Mix - 2 of Each)',
  },
  {
    id: 16,
    product:
      'Neutrogena Hydro Boost Hyaluronic Acid Hydrating Water Face Gel Moisturizer for Dry Skin, 1.7 fl. oz',
    price: 165,
    stock: 32,
    sales: 65,
    description: 'Water Face Gel Moisturizer for Dry Skin, 1.7 fl. oz',
  },
  {
    id: 17,
    product: 'Palmers Cocoa Butter Formula Moisturizing Skin Therapy Oil',
    price: 165,
    stock: 32,
    sales: 65,
    description: 'Face with Vitamin E Rosehip Fragrance Rose, 1 Fl Oz',
  },
  {
    id: 18,
    product: 'REVLON Oil-Absorbing Volcanic Face Roller',
    price: 165,
    stock: 32,
    sales: 65,
    description: 'Reusable Facial Skincare Tool for At-Home or On-the-Go Mini Massage',
  },
  {
    id: 19,
    product: 'Ice Face Roller Cube Tray for Eye, Neck, Brighten Skin & Enhance Your Natural Glow',
    price: 165,
    stock: 32,
    sales: 65,
    description: 'Reusable Beauty Facial Skin Care Tools',
  },
  {
    id: 20,
    product: 'Carpe Antiperspirant Hand and Foot Lotion Package Deal ',
    price: 165,
    stock: 32,
    sales: 65,
    description: 'Carpe Antiperspirant Hand and Foot Lotion Package Deal ',
  },
];
