export const dataTable = [
  {
    id: 1,
    product: 'Gorgeous Rubber Gloves',
    price: 165,
    stock: 32,
    sales: 65,
    description: 'High quality with Competitive Price',
  },
  {
    id: 2,
    product: 'Volumizer Hot Air Brush',
    price: 34,
    stock: 56,
    sales: 19,
    description: 'Less Frizz and helps reduce hair damage',
  },
  {
    id: 3,
    product: 'French Terry Jogger',
    price: 165,
    stock: 32,
    sales: 65,
    description: 'Athletic pant in lightweight French terry fabrication',
  },
  {
    id: 4,
    product: 'Gorgeous Plastic Tuna',
    price: 165,
    stock: 32,
    sales: 65,
    description: 'High quality with Competitive Price',
  },
  {
    id: 5,
    product: 'Tasty Concrete Hat',
    price: 165,
    stock: 32,
    sales: 65,
    description: 'High quality with Competitive Price',
  },
  {
    id: 6,
    product: 'Humidifier Mineral Absorption ',
    price: 165,
    stock: 32,
    sales: 65,
    description: '10 x absorption pads per packaged box',
  },
  {
    id: 7,
    product: 'Dramatic Faux Mink Eyelashes Pack',
    price: 165,
    stock: 32,
    sales: 65,
    description: 'Using the premium materials',
  },
];
