export { default as Dashboard } from './Dashboard/Dashboard';
export { default as Analytics } from './Analytics/Analytics';
export { default as Login } from './Login/Login';
// export { default as Transactions } from './Transactions/Transactions';
export { default as Products } from './Products/Products';
export { default as AddProduct } from './Products/AddProduct';
// export { default as ProductDetails } from './Products/ProductDetails';
// export { default as Categories } from './Products/Categories';
export { default as Category } from './Category/Category';
export { default as Users } from './Users/Users';
export { default as AddUser } from './Users/AddUser';
export { default as EditUser } from './Users/EditUser';
export { default as Account } from './Account/Account';
export { default as ChangePass } from './Account/ChangePass';
export { default as Sales } from './Sales/Sales';
export { default as AddSale } from './Sales/AddSale';
export { default as SaleDetails } from './Sales/SaleDetails';
export { default as Purchases } from './Purchases/Purchases';
export { default as AddPurchases } from './Purchases/AddPurchases';
export { default as PurchaseDetails } from './Purchases/PurchaseDetails';
export { default as Branches } from './Branches/Branches';
export { default as AddBranches } from './Branches/AddBranches';
export { default as Suppliers } from './Suppliers/Suppliers';
export { default as AddSupplier } from './Suppliers/AddSupplier';
export { default as Help } from './Help/Help';
export { default as NotFound } from './NotFound';
