let data = [
  {
    createdAt: '2022-01-19T18:15:13.554Z',
    title: 'Generic Rubber Tuna',
    image: 'http://placeimg.com/640/480/food',
    price: '7.00',
    stock: 55,
    description:
      'Ergonomic executive chair upholstered in bonded black leather and PVC padded seat and back for all-day comfort and support',
    category: 'Sports',
    id: '1',
    userId: '1',
  },
  {
    createdAt: '2022-01-19T23:08:03.433Z',
    title: 'Rustic Granite Keyboard',
    image: 'http://placeimg.com/640/480/food',
    price: '989.00',
    stock: 35,
    description:
      'The slim & simple Maple Gaming Keyboard from Dev Byte comes with a sleek body and 7- Color RGB LED Back-lighting for smart functionality',
    category: 'Health',
    id: '2',
    userId: '2',
  },
  {
    createdAt: '2022-01-19T22:02:19.039Z',
    title: 'Handcrafted Cotton Pizza',
    image: 'http://placeimg.com/640/480/food',
    price: '746.00',
    stock: 21,
    description:
      'New range of formal shirts are designed keeping you in mind. With fits and styling that will make you stand apart',
    category: 'Health',
    id: '3',
    userId: '3',
  },
  {
    createdAt: '2022-01-20T16:06:22.018Z',
    title: 'Ergonomic Frozen Chair',
    image: 'http://placeimg.com/640/480/food',
    price: '119.00',
    stock: 8,
    description:
      'The Nagasaki Lander is the trademarked name of several series of Nagasaki sport bikes, that started with the 1984 ABC800J',
    category: 'Music',
    id: '4',
    userId: '4',
  },
  {
    createdAt: '2022-01-20T16:07:44.827Z',
    title: 'Tasty Cotton Shoes',
    image: 'http://placeimg.com/640/480/food',
    price: '690.00',
    stock: 86,
    description:
      'New ABC 13 9370, 13.3, 5th Gen CoreA5-8250U, 8GB RAM, 256GB SSD, power UHD Graphics, OS 10 Home, OS Office A & J 2016',
    category: 'Books',
    id: '5',
    userId: '5',
  },
  {
    createdAt: '2022-01-20T04:47:14.519Z',
    title: 'Intelligent Rubber Soap',
    image: 'http://placeimg.com/640/480/food',
    price: '418.00',
    stock: 17,
    description:
      'The beautiful range of Apple Naturalé that has an exciting mix of natural ingredients. With the Goodness of 100% Natural Ingredients',
    category: 'Movies',
    id: '6',
    userId: '6',
  },
  {
    createdAt: '2022-01-19T23:56:52.775Z',
    title: 'Unbranded Metal Keyboard',
    image: 'http://placeimg.com/640/480/food',
    price: '737.00',
    stock: 39,
    description:
      'The beautiful range of Apple Naturalé that has an exciting mix of natural ingredients. With the Goodness of 100% Natural Ingredients',
    category: 'Books',
    id: '7',
    userId: '1',
  },
  {
    createdAt: '2022-01-20T03:41:26.081Z',
    title: 'Gorgeous Wooden Cheese',
    image: 'http://placeimg.com/640/480/food',
    price: '132.00',
    stock: 83,
    description:
      'Andy shoes are designed to keeping in mind durability as well as trends, the most stylish range of shoes & sandals',
    category: 'Games',
    id: '8',
    userId: '2',
  },
  {
    createdAt: '2022-01-20T07:28:39.568Z',
    title: 'Incredible Steel Chair',
    image: 'http://placeimg.com/640/480/food',
    price: '927.00',
    stock: 34,
    description:
      'The Nagasaki Lander is the trademarked name of several series of Nagasaki sport bikes, that started with the 1984 ABC800J',
    category: 'Beauty',
    id: '9',
    userId: '3',
  },
  {
    createdAt: '2022-01-20T09:06:34.120Z',
    title: 'Fantastic Concrete Gloves',
    image: 'http://placeimg.com/640/480/food',
    price: '570.00',
    stock: 9,
    description:
      'New ABC 13 9370, 13.3, 5th Gen CoreA5-8250U, 8GB RAM, 256GB SSD, power UHD Graphics, OS 10 Home, OS Office A & J 2016',
    category: 'Music',
    id: '10',
    userId: '4',
  },
  {
    createdAt: '2022-01-19T19:56:57.251Z',
    title: 'Handmade Cotton Car',
    image: 'http://placeimg.com/640/480/food',
    price: '914.00',
    stock: 22,
    description:
      'The Apollotech B340 is an affordable wireless mouse with reliable connectivity, 12 months battery life and modern design',
    category: 'Movies',
    id: '11',
    userId: '5',
  },
  {
    createdAt: '2022-01-20T13:03:25.736Z',
    title: 'Licensed Wooden Table',
    image: 'http://placeimg.com/640/480/food',
    price: '8.00',
    stock: 22,
    description:
      'The beautiful range of Apple Naturalé that has an exciting mix of natural ingredients. With the Goodness of 100% Natural Ingredients',
    category: 'Health',
    id: '12',
    userId: '6',
  },
  {
    createdAt: '2022-01-20T08:22:09.235Z',
    title: 'Handmade Concrete Fish',
    image: 'http://placeimg.com/640/480/food',
    price: '368.00',
    stock: 5,
    description:
      'The Apollotech B340 is an affordable wireless mouse with reliable connectivity, 12 months battery life and modern design',
    category: 'Home',
    id: '13',
    userId: '1',
  },
  {
    createdAt: '2022-01-19T18:43:51.647Z',
    title: 'Sleek Cotton Ball',
    image: 'http://placeimg.com/640/480/food',
    price: '94.00',
    stock: 86,
    description: 'The Football Is Good For Training And Recreational Purposes',
    category: 'Music',
    id: '14',
    userId: '2',
  },
  {
    createdAt: '2022-01-20T05:45:55.991Z',
    title: 'Unbranded Metal Table',
    image: 'http://placeimg.com/640/480/food',
    price: '455.00',
    stock: 11,
    description:
      'The slim & simple Maple Gaming Keyboard from Dev Byte comes with a sleek body and 7- Color RGB LED Back-lighting for smart functionality',
    category: 'Toys',
    id: '15',
    userId: '3',
  },
  {
    createdAt: '2022-01-20T06:04:02.121Z',
    title: 'Awesome Granite Fish',
    image: 'http://placeimg.com/640/480/food',
    price: '60.00',
    stock: 73,
    description:
      'The Nagasaki Lander is the trademarked name of several series of Nagasaki sport bikes, that started with the 1984 ABC800J',
    category: 'Home',
    id: '16',
    userId: '4',
  },
  {
    createdAt: '2022-01-19T17:09:24.285Z',
    title: 'Incredible Metal Shoes',
    image: 'http://placeimg.com/640/480/food',
    price: '748.00',
    stock: 55,
    description:
      'Andy shoes are designed to keeping in mind durability as well as trends, the most stylish range of shoes & sandals',
    category: 'Computers',
    id: '17',
    userId: '5',
  },
  {
    createdAt: '2022-01-19T20:42:28.140Z',
    title: 'Gorgeous Fresh Gloves',
    image: 'http://placeimg.com/640/480/food',
    price: '330.00',
    stock: 14,
    description:
      'Ergonomic executive chair upholstered in bonded black leather and PVC padded seat and back for all-day comfort and support',
    category: 'Kids',
    id: '18',
    userId: '6',
  },
  {
    createdAt: '2022-01-19T19:42:46.484Z',
    title: 'Tasty Fresh Shoes',
    image: 'http://placeimg.com/640/480/food',
    price: '581.00',
    stock: 60,
    description: 'Carbonite web goalkeeper gloves are ergonomically designed to give easy fit',
    category: 'Home',
    id: '19',
    userId: '1',
  },
  {
    createdAt: '2022-01-20T13:24:30.797Z',
    title: 'Practical Metal Gloves',
    image: 'http://placeimg.com/640/480/food',
    price: '494.00',
    stock: 99,
    description: 'Carbonite web goalkeeper gloves are ergonomically designed to give easy fit',
    category: 'Jewelery',
    id: '20',
    userId: '2',
  },
  {
    createdAt: '2022-01-20T12:06:32.934Z',
    title: 'Incredible Cotton Gloves',
    image: 'http://placeimg.com/640/480/food',
    price: '141.00',
    stock: 23,
    description:
      'The automobile layout consists of a front-engine design, with transaxle-type transmissions mounted at the rear of the engine and four wheel drive',
    category: 'Music',
    id: '21',
    userId: '3',
  },
  {
    createdAt: '2022-01-20T00:24:22.767Z',
    title: 'Handcrafted Metal Pizza',
    image: 'http://placeimg.com/640/480/food',
    price: '206.00',
    stock: 39,
    description:
      'The slim & simple Maple Gaming Keyboard from Dev Byte comes with a sleek body and 7- Color RGB LED Back-lighting for smart functionality',
    category: 'Beauty',
    id: '22',
    userId: '4',
  },
  {
    createdAt: '2022-01-20T07:00:32.887Z',
    title: 'Gorgeous Concrete Bacon',
    image: 'http://placeimg.com/640/480/food',
    price: '363.00',
    stock: 11,
    description:
      'The slim & simple Maple Gaming Keyboard from Dev Byte comes with a sleek body and 7- Color RGB LED Back-lighting for smart functionality',
    category: 'Automotive',
    id: '23',
    userId: '5',
  },
  {
    createdAt: '2022-01-20T00:08:16.783Z',
    title: 'Rustic Frozen Soap',
    image: 'http://placeimg.com/640/480/food',
    price: '578.00',
    stock: 67,
    description:
      'Ergonomic executive chair upholstered in bonded black leather and PVC padded seat and back for all-day comfort and support',
    category: 'Sports',
    id: '24',
    userId: '6',
  },
  {
    createdAt: '2022-01-20T15:53:03.865Z',
    title: 'Handcrafted Granite Cheese',
    image: 'http://placeimg.com/640/480/food',
    price: '342.00',
    stock: 32,
    description: 'The Football Is Good For Training And Recreational Purposes',
    category: 'Computers',
    id: '25',
    userId: '1',
  },
  {
    createdAt: '2022-01-19T21:24:34.306Z',
    title: 'Ergonomic Concrete Bacon',
    image: 'http://placeimg.com/640/480/food',
    price: '245.00',
    stock: 99,
    description:
      "Boston's most advanced compression wear technology increases muscle oxygenation, stabilizes active muscles",
    category: 'Toys',
    id: '26',
    userId: '2',
  },
  {
    createdAt: '2022-01-20T15:51:04.748Z',
    title: 'Ergonomic Frozen Salad',
    image: 'http://placeimg.com/640/480/food',
    price: '854.00',
    stock: 89,
    description:
      'The Apollotech B340 is an affordable wireless mouse with reliable connectivity, 12 months battery life and modern design',
    category: 'Tools',
    id: '27',
    userId: '3',
  },
  {
    createdAt: '2022-01-20T12:19:33.898Z',
    title: 'Generic Granite Mouse',
    image: 'http://placeimg.com/640/480/food',
    price: '211.00',
    stock: 66,
    description:
      'The Nagasaki Lander is the trademarked name of several series of Nagasaki sport bikes, that started with the 1984 ABC800J',
    category: 'Sports',
    id: '28',
    userId: '4',
  },
  {
    createdAt: '2022-01-20T01:27:34.170Z',
    title: 'Generic Rubber Chicken',
    image: 'http://placeimg.com/640/480/food',
    price: '753.00',
    stock: 37,
    description:
      'Andy shoes are designed to keeping in mind durability as well as trends, the most stylish range of shoes & sandals',
    category: 'Outdoors',
    id: '29',
    userId: '5',
  },
  {
    createdAt: '2022-01-20T01:19:23.360Z',
    title: 'Unbranded Steel Gloves',
    image: 'http://placeimg.com/640/480/food',
    price: '105.00',
    stock: 56,
    description:
      'The Apollotech B340 is an affordable wireless mouse with reliable connectivity, 12 months battery life and modern design',
    category: 'Health',
    id: '30',
    userId: '6',
  },
  {
    createdAt: '2022-01-19T22:14:45.192Z',
    title: 'Incredible Wooden Shoes',
    image: 'http://placeimg.com/640/480/food',
    price: '465.00',
    stock: 17,
    description:
      'The Apollotech B340 is an affordable wireless mouse with reliable connectivity, 12 months battery life and modern design',
    category: 'Kids',
    id: '31',
    userId: '1',
  },
  {
    createdAt: '2022-01-20T06:25:37.960Z',
    title: 'Practical Plastic Car',
    image: 'http://placeimg.com/640/480/food',
    price: '71.00',
    stock: 17,
    description:
      'The slim & simple Maple Gaming Keyboard from Dev Byte comes with a sleek body and 7- Color RGB LED Back-lighting for smart functionality',
    category: 'Clothing',
    id: '32',
    userId: '2',
  },
  {
    createdAt: '2022-01-20T06:31:06.977Z',
    title: 'Incredible Metal Soap',
    image: 'http://placeimg.com/640/480/food',
    price: '846.00',
    stock: 6,
    description: 'Carbonite web goalkeeper gloves are ergonomically designed to give easy fit',
    category: 'Automotive',
    id: '33',
    userId: '3',
  },
  {
    createdAt: '2022-01-20T03:04:33.602Z',
    title: 'Sleek Concrete Chair',
    image: 'http://placeimg.com/640/480/food',
    price: '15.00',
    stock: 17,
    description:
      'New range of formal shirts are designed keeping you in mind. With fits and styling that will make you stand apart',
    category: 'Kids',
    id: '34',
    userId: '4',
  },
  {
    createdAt: '2022-01-20T05:29:41.663Z',
    title: 'Intelligent Steel Car',
    image: 'http://placeimg.com/640/480/food',
    price: '439.00',
    stock: 88,
    description:
      'New range of formal shirts are designed keeping you in mind. With fits and styling that will make you stand apart',
    category: 'Books',
    id: '35',
    userId: '5',
  },
  {
    createdAt: '2022-01-20T11:18:10.173Z',
    title: 'Intelligent Steel Pizza',
    image: 'http://placeimg.com/640/480/food',
    price: '339.00',
    stock: 38,
    description:
      'The Apollotech B340 is an affordable wireless mouse with reliable connectivity, 12 months battery life and modern design',
    category: 'Home',
    id: '36',
    userId: '6',
  },
  {
    createdAt: '2022-01-19T19:41:05.216Z',
    title: 'Small Wooden Tuna',
    image: 'http://placeimg.com/640/480/food',
    price: '471.00',
    stock: 10,
    description:
      'Ergonomic executive chair upholstered in bonded black leather and PVC padded seat and back for all-day comfort and support',
    category: 'Grocery',
    id: '37',
    userId: '1',
  },
  {
    createdAt: '2022-01-20T12:44:30.116Z',
    title: 'Gorgeous Soft Gloves',
    image: 'http://placeimg.com/640/480/food',
    price: '710.00',
    stock: 61,
    description: 'Carbonite web goalkeeper gloves are ergonomically designed to give easy fit',
    category: 'Kids',
    id: '38',
    userId: '2',
  },
  {
    createdAt: '2022-01-20T06:14:51.251Z',
    title: 'Awesome Steel Ball',
    image: 'http://placeimg.com/640/480/food',
    price: '638.00',
    stock: 9,
    description:
      'The Apollotech B340 is an affordable wireless mouse with reliable connectivity, 12 months battery life and modern design',
    category: 'Health',
    id: '39',
    userId: '3',
  },
  {
    createdAt: '2022-01-20T07:28:36.878Z',
    title: 'Licensed Concrete Pants',
    image: 'http://placeimg.com/640/480/food',
    price: '826.00',
    stock: 77,
    description:
      'The Apollotech B340 is an affordable wireless mouse with reliable connectivity, 12 months battery life and modern design',
    category: 'Home',
    id: '40',
    userId: '4',
  },
  {
    createdAt: '2022-01-20T06:59:42.341Z',
    title: 'Incredible Fresh Bike',
    image: 'http://placeimg.com/640/480/food',
    price: '183.00',
    stock: 7,
    description: 'Carbonite web goalkeeper gloves are ergonomically designed to give easy fit',
    category: 'Books',
    id: '41',
    userId: '5',
  },
  {
    createdAt: '2022-01-20T05:07:44.589Z',
    title: 'Refined Wooden Pants',
    image: 'http://placeimg.com/640/480/food',
    price: '26.00',
    stock: 46,
    description:
      'New ABC 13 9370, 13.3, 5th Gen CoreA5-8250U, 8GB RAM, 256GB SSD, power UHD Graphics, OS 10 Home, OS Office A & J 2016',
    category: 'Industrial',
    id: '42',
    userId: '6',
  },
  {
    createdAt: '2022-01-20T08:42:42.502Z',
    title: 'Generic Concrete Shirt',
    image: 'http://placeimg.com/640/480/food',
    price: '896.00',
    stock: 64,
    description:
      'The slim & simple Maple Gaming Keyboard from Dev Byte comes with a sleek body and 7- Color RGB LED Back-lighting for smart functionality',
    category: 'Industrial',
    id: '43',
    userId: '1',
  },
  {
    createdAt: '2022-01-19T16:53:14.074Z',
    title: 'Gorgeous Plastic Tuna',
    image: 'http://placeimg.com/640/480/food',
    price: '597.00',
    stock: 73,
    description:
      'New range of formal shirts are designed keeping you in mind. With fits and styling that will make you stand apart',
    category: 'Grocery',
    id: '44',
    userId: '2',
  },
  {
    createdAt: '2022-01-20T07:24:13.042Z',
    title: 'Intelligent Plastic Cheese',
    image: 'http://placeimg.com/640/480/food',
    price: '254.00',
    stock: 52,
    description:
      'New ABC 13 9370, 13.3, 5th Gen CoreA5-8250U, 8GB RAM, 256GB SSD, power UHD Graphics, OS 10 Home, OS Office A & J 2016',
    category: 'Automotive',
    id: '45',
    userId: '3',
  },
  {
    createdAt: '2022-01-19T21:19:55.745Z',
    title: 'Gorgeous Rubber Sausages',
    image: 'http://placeimg.com/640/480/food',
    price: '750.00',
    stock: 29,
    description: 'The Football Is Good For Training And Recreational Purposes',
    category: 'Computers',
    id: '46',
    userId: '4',
  },
  {
    createdAt: '2022-01-20T12:46:41.379Z',
    title: 'Refined Granite Chicken',
    image: 'http://placeimg.com/640/480/food',
    price: '998.00',
    stock: 7,
    description: 'The Football Is Good For Training And Recreational Purposes',
    category: 'Games',
    id: '47',
    userId: '5',
  },
  {
    createdAt: '2022-01-20T12:24:25.190Z',
    title: 'Incredible Fresh Ball',
    image: 'http://placeimg.com/640/480/food',
    price: '225.00',
    stock: 22,
    description:
      'New ABC 13 9370, 13.3, 5th Gen CoreA5-8250U, 8GB RAM, 256GB SSD, power UHD Graphics, OS 10 Home, OS Office A & J 2016',
    category: 'Baby',
    id: '48',
    userId: '1',
  },
  {
    createdAt: '2022-01-19T19:16:23.168Z',
    title: 'Unbranded Wooden Chair',
    image: 'http://placeimg.com/640/480/food',
    price: '698.00',
    stock: 52,
    description:
      'New range of formal shirts are designed keeping you in mind. With fits and styling that will make you stand apart',
    category: 'Kids',
    id: '49',
    userId: '2',
  },
  {
    createdAt: '2022-01-19T21:58:17.652Z',
    title: 'Tasty Plastic Fish',
    image: 'http://placeimg.com/640/480/food',
    price: '46.00',
    stock: 0,
    description:
      'The automobile layout consists of a front-engine design, with transaxle-type transmissions mounted at the rear of the engine and four wheel drive',
    category: 'Grocery',
    id: '50',
    userId: '3',
  },
];

export const getAllProducts = () => {
  return data;
};

export const getProductById = id => {
  return data.find(item => Number(item.id) === id);
};
